In [4]:
import numpy as np 
import pandas as pd

Creating a dataframe

In [6]:
data ={
    "Name": ['A', 'B', 'C', 'D'],
    "Age": ['10', '20', '30', '40'],
    "City": ['jal', 'una', 'kullu', 'jaipur'],
    "Salary": ['25', '35', '45', '55']
}

In [9]:
df =pd.DataFrame(data)
df

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55

In [14]:
list = [
    ['A', '10', 'jal', '25'],
    ['B', '20', 'una', '35'],
    ['C', '30', 'kullu', '45'],
    ['D', '40', 'jaipur', '55']
]
labels = ['Name', 'Age', 'City', 'Salary']

In [12]:
df2 = pd.DataFrame(list)
df2

   0   1       2   3
0  A  10     jal  25
1  B  20     una  35
2  C  30   kullu  45
3  D  40  jaipur  55

In [15]:
df3 = pd.DataFrame(list, columns=labels)
df3

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55