In [4]:
import numpy as np 
import pandas as pd

Creating a dataframe

In [5]:
data ={
    "Name": ['A', 'B', 'C', 'D'],
    "Age": ['10', '20', '30', '40'],
    "City": ['jal', 'una', 'kullu', 'jaipur'],
    "Salary": ['25', '35', '45', '55']
}

In [6]:
df =pd.DataFrame(data)
df
#in dictionary the columns are the keys and the values are the list of values for each column. The DataFrame is created by passing the dictionary to the pd.DataFrame() function.

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55

In [7]:
list = [
    ['A', '10', 'jal', '25'],
    ['B', '20', 'una', '35'],
    ['C', '30', 'kullu', '45'],
    ['D', '40', 'jaipur', '55']
]
labels = ['Name', 'Age', 'City', 'Salary']

In [8]:
df2 = pd.DataFrame(list)
df2
#in list column names are not provided, so pandas assigns default column names as 0, 1, 2, 3.

   0   1       2   3
0  A  10     jal  25
1  B  20     una  35
2  C  30   kullu  45
3  D  40  jaipur  55

In [9]:
df3 = pd.DataFrame(list, columns=labels)
df3
#in list we can customize the column names by passing a list of column names to the columns parameter of the pd.DataFrame() function.

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55

Selection and indexing of columns

In [12]:
df3

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55

In [14]:
df3['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: object

In [15]:
df3['City']

0       jal
1       una
2     kullu
3    jaipur
Name: City, dtype: object

In [16]:
df3[["Name","City"]]

  Name    City
0    A     jal
1    B     una
2    C   kullu
3    D  jaipur

Creating a new column

In [17]:
df3["Designation"] = ['Manager', 'Team Lead', 'Senior Developer', 'Junior Developer']

In [20]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

Removing columns

In [23]:
df3.drop('Designation',axis=1)

  Name Age    City Salary
0    A  10     jal     25
1    B  20     una     35
2    C  30   kullu     45
3    D  40  jaipur     55

In [24]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

In [26]:
df3.drop(["City", "Salary"], axis=1)

  Name Age       Designation
0    A  10           Manager
1    B  20         Team Lead
2    C  30  Senior Developer
3    D  40  Junior Developer

In [27]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

Selecting rows

In [29]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

In [30]:
df3.loc[[0,1]]

  Name Age City Salary Designation
0    A  10  jal     25     Manager
1    B  20  una     35   Team Lead

In [31]:
df.iloc[3]

Name           D
Age           40
City      jaipur
Salary        55
Name: 3, dtype: object

In [32]:
df.loc[[0,1]][["City","Salary"]]

  City Salary
0  jal     25
1  una     35

Selecting subsets of rows and columns

In [33]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

In [34]:
#I only want to see those people whose age is above 30

In [ ]:
df3[df3["Age"] > 30]

In [40]:
#I only want people whose age is above 30 and their city must be parts

In [ ]:
df3[(df3["Age"]>30)&(df3["City"]=="jaipur")]

Conditional selection

In [45]:
df3

  Name Age    City Salary       Designation
0    A  10     jal     25           Manager
1    B  20     una     35         Team Lead
2    C  30   kullu     45  Senior Developer
3    D  40  jaipur     55  Junior Developer

In [46]:
#I only want to see those people whose age is above 30

In [ ]:
df3[df3["Age"] > 30]

In [49]:
#I onlly want people whose age is above 30 and their city must be jaipur

In [ ]:
df3[(df3["Age"]>30)&(df3["City"]=="jaipur")]